// Copyright 2026 Dao Browser Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "dao/browser/agent/workspace/workspace_index.h"

#include <algorithm>
#include <string>
#include <vector>

#include "base/files/file_enumerator.h"
#include "base/files/file_util.h"
#include "base/i18n/time_formatting.h"
#include "base/strings/strcat.h"
#include "base/strings/stringprintf.h"
#include "base/strings/utf_string_conversions.h"
#include "base/time/time.h"

namespace dao {

namespace {

constexpr char kIndexFileName[] = "WORKSPACE.md";

struct FileRow {
  std::string rel_path;
  int64_t bytes = 0;
  int line_count = -1;  // -1 if not counted (non-md)
};

bool IsBookkeeping(const base::FilePath::StringType& name) {
  return name == FILE_PATH_LITERAL(".audit.log") ||
         name == FILE_PATH_LITERAL("WORKSPACE.md");
}

std::string FormatSize(int64_t bytes) {
  if (bytes < 1024) {
    return base::StringPrintf("%lld B", static_cast<long long>(bytes));
  }
  if (bytes < 1024 * 1024) {
    return base::StringPrintf("%.1f KB", bytes / 1024.0);
  }
  return base::StringPrintf("%.1f MB", bytes / (1024.0 * 1024.0));
}

}  // namespace

WorkspaceIndex::WorkspaceIndex(const base::FilePath& workspace_root)
    : workspace_root_(workspace_root) {}

WorkspaceIndex::~WorkspaceIndex() = default;

void WorkspaceIndex::Rewrite() {
  std::vector<FileRow> rows;
  int64_t total = 0;

  base::FileEnumerator enumerator(
      workspace_root_, /*recursive=*/true, base::FileEnumerator::FILES);
  for (base::FilePath path = enumerator.Next(); !path.empty();
       path = enumerator.Next()) {
    base::FilePath relative;
    if (!workspace_root_.AppendRelativePath(path, &relative)) {
      continue;
    }
    auto comps = relative.GetComponents();
    if (comps.empty()) {
      continue;
    }
    if (IsBookkeeping(comps[0])) {
      continue;
    }
    if (comps[0] == FILE_PATH_LITERAL(".workspace_tmp")) {
      continue;
    }

    FileRow row;
    row.rel_path = relative.AsUTF8Unsafe();
    row.bytes = enumerator.GetInfo().GetSize();
    row.line_count = -1;
    // Count lines for .md files only — cheap heuristic.
    if (relative.MatchesExtension(FILE_PATH_LITERAL(".md"))) {
      std::string body;
      if (base::ReadFileToString(path, &body)) {
        row.line_count = static_cast<int>(
            std::count(body.begin(), body.end(), '\n'));
      }
    }
    total += row.bytes;
    rows.push_back(std::move(row));
  }

  std::sort(rows.begin(), rows.end(),
            [](const FileRow& a, const FileRow& b) {
              return a.rel_path < b.rel_path;
            });

  std::string out;
  out += "<!-- Auto-generated by Dao Agent. DO NOT EDIT — "
         "your changes will be overwritten. -->\n";
  out += "# Workspace Index\n\n";
  out += "Last updated: ";
  out += base::UTF16ToUTF8(
      base::TimeFormatShortDateAndTime(base::Time::Now()));
  out += "\n\n## Files\n";
  if (rows.empty()) {
    out += "(none)\n";
  } else {
    for (const auto& r : rows) {
      out += "- `";
      out += r.rel_path;
      out += "` (";
      out += FormatSize(r.bytes);
      if (r.line_count >= 0) {
        out += base::StringPrintf(", %d lines", r.line_count);
      }
      out += ")\n";
    }
  }
  out += "\n## Stats\n";
  out += base::StringPrintf("- %zu files, %s total\n", rows.size(),
                            FormatSize(total).c_str());
  out += base::StringPrintf("- Quota: %s / 100 MB used\n",
                            FormatSize(total).c_str());

  base::WriteFile(workspace_root_.AppendASCII(kIndexFileName), out);
}

}  // namespace dao
