// Auto-generated by scripts/i18n-bootstrap.ts. Empty entries fall back to en.
// Lang: he
import en from './en.js';
import type { Dictionary } from '../i18n.js';

const dict: Dictionary = {
  ...en,
  // Override entries here as translations land.
};

export default dict;
