// Copyright 2026 Dao Browser Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Generates readability_bundle.ts containing the minified @mozilla/readability
// as an injectable script string for the agent's get_readable_content tool.

import {execSync} from 'child_process';
import {writeFileSync, readFileSync} from 'fs';
import {resolve, dirname} from 'path';
import {fileURLToPath} from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

// Bundle Readability.js into a minified IIFE
const bundle = execSync(
  'npx esbuild node_modules/@mozilla/readability/Readability.js ' +
  '--bundle --minify --format=iife --global-name=ReadabilityModule',
  {cwd: root, encoding: 'utf8'}
).trim();

// Build the injection script: load Readability, clone the document, parse,
// and return the extracted article.
const injectScript = `(function() {
  ${bundle}
  var Readability = ReadabilityModule;
  var clone = document.cloneNode(true);
  var article = new Readability(clone).parse();
  if (!article) return JSON.stringify({error: 'Could not extract readable content'});
  return JSON.stringify({
    title: article.title || '',
    byline: article.byline || '',
    excerpt: article.excerpt || '',
    siteName: article.siteName || '',
    length: article.length || 0,
    textContent: article.textContent || ''
  });
})()`;

// Escape backticks and backslashes for template literal embedding
const escaped = injectScript
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

const output = `// Copyright 2026 Dao Browser Authors. All rights reserved.
// Auto-generated by scripts/gen_readability_bundle.ts — do not edit manually.

// Minified @mozilla/readability IIFE + execution wrapper.
// Injected into the target page via DevTools Runtime.evaluate to extract
// the main article content.
export const READABILITY_INJECT_SCRIPT = \`${escaped}\`;
`;

const outPath = resolve(
  root,
  'src/dao/browser/ui/webui/resources/agent/readability_bundle.ts'
);
writeFileSync(outPath, output, 'utf8');
console.log('Generated', outPath, `(${output.length} bytes)`);
