// Copyright 2026 Dao Browser Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// `npm run vendor` — bundle vendored npm dependencies declared in
// /vendor.config.ts into artifacts inside the Chromium WebUI resource tree.
// See /vendor/README.md for the full contract.

import { Command } from "commander";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { log, success, warn, error, ROOT_DIR, runStreaming } from "../utils.js";
import type {
  VendorConfig,
  VendorEntry,
  VendorFormat,
} from "../../vendor.config.js";

const VENDOR_DIR = path.join(ROOT_DIR, "vendor");
const MANIFEST_PATH = path.join(VENDOR_DIR, "manifest.json");

interface ManifestEntry {
  name: string;
  format: VendorFormat;
  outFile: string;
  pkgVersions: Record<string, string>;
  sha256: string;
  generatedAt: string;
}

interface Manifest {
  entries: ManifestEntry[];
}

async function loadConfig(): Promise<VendorConfig> {
  const configPath = path.join(ROOT_DIR, "vendor.config.ts");
  if (!existsSync(configPath)) {
    throw new Error(`vendor.config.ts not found at ${configPath}`);
  }
  const mod = await import(pathToFileURL(configPath).href);
  const cfg = (mod.default ?? mod) as VendorConfig;
  if (!cfg || !Array.isArray(cfg.entries)) {
    throw new Error("vendor.config.ts must default-export { entries: [...] }");
  }
  return cfg;
}

function loadManifest(): Manifest {
  if (!existsSync(MANIFEST_PATH)) return { entries: [] };
  return JSON.parse(readFileSync(MANIFEST_PATH, "utf-8")) as Manifest;
}

function saveManifest(m: Manifest): void {
  writeFileSync(MANIFEST_PATH, JSON.stringify(m, null, 2) + "\n", "utf-8");
}

function sha256(buf: Buffer | string): string {
  return createHash("sha256").update(buf).digest("hex");
}

function readPkgVersions(names: string[]): Record<string, string> {
  const pkgJsonPath = path.join(VENDOR_DIR, "package.json");
  const raw = JSON.parse(readFileSync(pkgJsonPath, "utf-8")) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };
  const merged = { ...(raw.devDependencies ?? {}), ...(raw.dependencies ?? {}) };
  const out: Record<string, string> = {};
  for (const n of names) {
    const v = merged[n];
    if (!v) {
      throw new Error(
        `vendor/package.json is missing "${n}" — add it with ` +
          `\`cd vendor && npm install ${n}@<version> --save\``
      );
    }
    out[n] = v;
  }
  return out;
}

async function ensureInstalled(): Promise<void> {
  const nodeModules = path.join(VENDOR_DIR, "node_modules");
  if (existsSync(nodeModules)) return;
  log("vendor/node_modules missing — running `npm install` in vendor/…");
  const code = await runStreaming("npm", ["install", "--no-audit", "--no-fund"], {
    cwd: VENDOR_DIR,
  });
  if (code !== 0) throw new Error(`npm install failed with exit ${code}`);
}

function autoGeneratedHeader(entry: VendorEntry, versions: Record<string, string>): string {
  const pkgList = Object.entries(versions)
    .map(([k, v]) => `${k}@${v}`)
    .join(", ");
  // When the output is committed as a `.ts` file inside a `build_webui`
  // resource tree, Chromium's TS library would otherwise try to type-check
  // a 1–2 MB minified bundle. Suppress that with `@ts-nocheck`.
  const maybeTsNoCheck = entry.format === "esm" && entry.outName.endsWith(".ts")
    ? `// @ts-nocheck\n/* eslint-disable */\n`
    : "";
  return (
    `// Copyright 2026 Dao Browser Authors. All rights reserved.\n` +
    `// Auto-generated by \`npm run vendor -- --entry=${entry.name}\`. DO NOT EDIT.\n` +
    `// Source: ${pkgList}\n` +
    `// Format: ${entry.format}\n` +
    maybeTsNoCheck
  );
}

async function buildEsm(
  entry: VendorEntry,
  versions: Record<string, string>
): Promise<{ outPath: string; bytes: Buffer }> {
  if (!entry.entry) {
    throw new Error(`Entry "${entry.name}": format=esm requires \`entry\`.`);
  }
  const entryPath = path.join(ROOT_DIR, entry.entry);
  if (!existsSync(entryPath)) {
    throw new Error(`Entry file not found: ${entryPath}`);
  }
  const outDir = path.join(ROOT_DIR, entry.outDir);
  mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, entry.outName);

  // Dynamic import so esbuild only loads when actually needed.
  const esbuild = (await import(
    pathToFileURL(path.join(VENDOR_DIR, "node_modules", "esbuild", "lib", "main.js")).href
  )) as typeof import("esbuild");

  // `external: [...]` leaves bare `import "pkg"` statements in the emitted
  // ESM bundle — browsers can't resolve bare specifiers, so any reachable
  // top-level import of an external pkg throws at module-load time. For
  // browser targets we instead replace these specifiers with an inline
  // empty-namespace stub so the import is erased from the output. Any
  // code path that actually *calls* into one of the stubbed deps will
  // throw a clear "is not a function" at runtime — that's fine, our
  // usage guarantees none of these paths are ever entered.
  const externalSpecs = entry.external ?? [];
  const shimPlugin = externalSpecs.length === 0 ? null : {
    name: "dao-stub-externals",
    setup(build: import("esbuild").PluginBuild) {
      const matchers = externalSpecs.map((spec) => {
        if (spec.endsWith("/*")) {
          const prefix = spec.slice(0, -1);
          return (id: string) => id === prefix.slice(0, -1) || id.startsWith(prefix);
        }
        return (id: string) => id === spec || id.startsWith(spec + "/");
      });
      build.onResolve({ filter: /.*/ }, (args) => {
        if (matchers.some((m) => m(args.path))) {
          return { path: args.path, namespace: "dao-stub" };
        }
        return null;
      });
      // ESM stub. Key names below cover every accessor pi-web-ui
      // touches at module load; __stubObj is a recursive Proxy so
      // `stub.GlobalWorkerOptions.workerSrc = "…"` succeeds silently
      // and `new stub.Ollama()` / `stub.getDocument()` throw only if
      // actually invoked. Emitting ESM (not CJS) avoids esbuild's
      // __toESM own-key copy which drops Proxy keys.
      build.onLoad({ filter: /.*/, namespace: "dao-stub" }, (args) => {
        const stubbedNames = [
          "GlobalWorkerOptions", "getDocument", "version",
          "parseAsync", "renderAsync",
          "read", "utils", "write",
          "LMStudioClient", "Ollama",
        ];
        const lines = [
          "const __name = " + JSON.stringify(args.path) + ";",
          "function __makeStub(path) {",
          "  const fn = function () {",
          "    throw new Error('Stubbed dep invoked: ' + __name + ' / ' + path);",
          "  };",
          "  return new Proxy(fn, {",
          "    get(target, prop) {",
          "      if (prop === '__esModule') return true;",
          "      if (typeof prop === 'symbol') return target[prop];",
          "      if (prop === 'then') return undefined;",
          "      return __makeStub(path + '.' + String(prop));",
          "    },",
          "    set() { return true; },",
          "    apply() { throw new Error('Stubbed dep called: ' + __name + ' / ' + path); },",
          "    construct() { throw new Error('Stubbed dep constructed: ' + __name + ' / ' + path); },",
          "  });",
          "}",
          "const __stubObj = __makeStub(__name);",
          "export default __stubObj;",
        ];
        for (const n of stubbedNames) {
          lines.push(`export const ${n} = __stubObj.${n};`);
        }
        return { contents: lines.join("\n") + "\n", loader: "js" };
      });
    },
  };

  await esbuild.build({
    entryPoints: [entryPath],
    bundle: true,
    format: "esm",
    target: entry.target ?? "es2022",
    minify: entry.minify ?? true,
    sourcemap: entry.sourcemap ?? true,
    outfile: outPath,
    absWorkingDir: VENDOR_DIR,
    nodePaths: [path.join(VENDOR_DIR, "node_modules")],
    legalComments: "none",
    logLevel: "warning",
    plugins: shimPlugin ? [shimPlugin] : [],
  });

  // Prepend the auto-generated header to the committed output.
  const header = autoGeneratedHeader(entry, versions);
  const body = readFileSync(outPath);
  const final = Buffer.concat([Buffer.from(header, "utf-8"), body]);
  writeFileSync(outPath, final);
  return { outPath, bytes: final };
}

async function buildIifeString(
  entry: VendorEntry,
  versions: Record<string, string>
): Promise<{ outPath: string; bytes: Buffer }> {
  if (!entry.entry) {
    throw new Error(
      `Entry "${entry.name}": format=iife-string requires \`entry\`.`
    );
  }
  if (!entry.wrapperTemplate) {
    throw new Error(
      `Entry "${entry.name}": format=iife-string requires \`wrapperTemplate\`.`
    );
  }
  const entryPath = path.join(ROOT_DIR, entry.entry);
  const wrapperPath = path.join(ROOT_DIR, entry.wrapperTemplate);
  if (!existsSync(entryPath)) {
    throw new Error(`Entry file not found: ${entryPath}`);
  }
  if (!existsSync(wrapperPath)) {
    throw new Error(`Wrapper template not found: ${wrapperPath}`);
  }
  const outDir = path.join(ROOT_DIR, entry.outDir);
  mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, entry.outName);

  const esbuild = (await import(
    pathToFileURL(path.join(VENDOR_DIR, "node_modules", "esbuild", "lib", "main.js")).href
  )) as typeof import("esbuild");

  // Bundle to a single IIFE string (no file written).
  const result = await esbuild.build({
    entryPoints: [entryPath],
    bundle: true,
    format: "iife",
    globalName: "__VendorModule",
    target: entry.target ?? "es2022",
    minify: entry.minify ?? true,
    write: false,
    absWorkingDir: VENDOR_DIR,
    nodePaths: [path.join(VENDOR_DIR, "node_modules")],
    legalComments: "none",
    logLevel: "warning",
  });
  if (result.outputFiles.length !== 1) {
    throw new Error(
      `Expected 1 output file for ${entry.name}, got ${result.outputFiles.length}`
    );
  }
  const bundle = result.outputFiles[0].text;

  // Load wrapper template and substitute __BUNDLE__ placeholder.
  const wrapperRaw = readFileSync(wrapperPath, "utf-8");
  if (!wrapperRaw.includes("__BUNDLE__")) {
    throw new Error(
      `Wrapper template ${entry.wrapperTemplate} must contain the __BUNDLE__ placeholder.`
    );
  }
  // Escape for template literal embedding: \ first, then backticks, then ${.
  // Use a function replacer to avoid interpreting `$&` / `$1` in bundle text.
  const escaped = bundle
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
  const body = wrapperRaw.replace("__BUNDLE__", () => escaped);
  const header = autoGeneratedHeader(entry, versions);
  const final = Buffer.from(header + body, "utf-8");
  writeFileSync(outPath, final);
  return { outPath, bytes: final };
}

async function buildCustom(
  entry: VendorEntry,
  versions: Record<string, string>
): Promise<{ outPath: string; bytes: Buffer }> {
  if (!entry.customBuild) {
    throw new Error(
      `Entry "${entry.name}": format=customBuild requires \`customBuild\`.`
    );
  }
  const scriptPath = path.join(ROOT_DIR, entry.customBuild);
  if (!existsSync(scriptPath)) {
    throw new Error(`customBuild script not found: ${scriptPath}`);
  }
  const outDir = path.join(ROOT_DIR, entry.outDir);
  mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, entry.outName);

  const env = {
    ...process.env,
    VENDOR_DIR,
    ROOT_DIR,
    ENTRY_OUT_PATH: outPath,
    ENTRY_NAME: entry.name,
  };
  const code = await runStreaming("node", [scriptPath], { cwd: VENDOR_DIR, env });
  if (code !== 0) {
    throw new Error(`customBuild for ${entry.name} exited with ${code}`);
  }
  if (!existsSync(outPath)) {
    throw new Error(
      `customBuild for ${entry.name} did not produce ${outPath}`
    );
  }
  // Prepend the header for consistency (CSS comment syntax handled elsewhere).
  const bytes = readFileSync(outPath);
  return { outPath, bytes };
}

async function buildEntry(
  entry: VendorEntry,
  opts: { check: boolean }
): Promise<void> {
  const versions = readPkgVersions(entry.npm);
  const outPath = path.join(ROOT_DIR, entry.outDir, entry.outName);
  const manifest = loadManifest();
  const existingIdx = manifest.entries.findIndex((e) => e.name === entry.name);

  // --check: read the on-disk artifact and compare its hash + pinned
  // versions against manifest.json. Never rebuild — that's the point of
  // a CI gate.
  if (opts.check) {
    const prev = existingIdx >= 0 ? manifest.entries[existingIdx] : null;
    if (!prev) {
      error(
        `Entry "${entry.name}": not in manifest.json. Run ` +
          `\`npm run vendor -- --entry=${entry.name}\` and commit the result.`
      );
      process.exitCode = 1;
      return;
    }
    if (!existsSync(outPath)) {
      error(
        `Entry "${entry.name}": artifact missing at ${path.relative(ROOT_DIR, outPath)}.`
      );
      process.exitCode = 1;
      return;
    }
    const bytes = readFileSync(outPath);
    const hash = sha256(bytes);
    if (prev.sha256 !== hash) {
      error(
        `Entry "${entry.name}": artifact drift (on-disk sha256 ${hash.slice(
          0,
          12
        )}… vs manifest ${prev.sha256.slice(0, 12)}…). Rebuild and commit.`
      );
      process.exitCode = 1;
      return;
    }
    const pinDrift = Object.entries(versions).some(
      ([k, v]) => prev.pkgVersions[k] !== v
    );
    if (pinDrift) {
      error(
        `Entry "${entry.name}": vendor/package.json versions changed but ` +
          `bundle was not rebuilt. Run \`npm run vendor -- --entry=${entry.name}\`.`
      );
      process.exitCode = 1;
      return;
    }
    success(`Entry "${entry.name}": in sync (sha256 ${hash.slice(0, 12)}…).`);
    return;
  }

  let built: { outPath: string; bytes: Buffer };
  if (entry.format === "esm") {
    built = await buildEsm(entry, versions);
  } else if (entry.format === "iife-string") {
    built = await buildIifeString(entry, versions);
  } else {
    built = await buildCustom(entry, versions);
  }

  const hash = sha256(built.bytes);
  const manifestEntry: ManifestEntry = {
    name: entry.name,
    format: entry.format,
    outFile: path.relative(ROOT_DIR, built.outPath),
    pkgVersions: versions,
    sha256: hash,
    generatedAt: new Date().toISOString(),
  };

  if (existingIdx >= 0) manifest.entries[existingIdx] = manifestEntry;
  else manifest.entries.push(manifestEntry);
  saveManifest(manifest);

  success(
    `Built ${entry.name} → ${path.relative(ROOT_DIR, built.outPath)} ` +
      `(${built.bytes.length} bytes, sha256 ${hash.slice(0, 12)}…)`
  );
}

export const vendorCommand = new Command("vendor")
  .description(
    "Bundle vendored npm dependencies declared in vendor.config.ts into " +
      "artifacts inside the WebUI resource tree."
  )
  .option("--entry <name>", "Only rebuild the entry with this name")
  .option("--check", "Verify on-disk artifacts match manifest.json (CI mode)")
  .option("--list", "List declared entries and their pinned versions")
  .action(
    async (opts: { entry?: string; check?: boolean; list?: boolean }) => {
      const config = await loadConfig();

      if (opts.list) {
        for (const e of config.entries) {
          const versions = readPkgVersions(e.npm);
          const v = Object.entries(versions)
            .map(([k, x]) => `${k}@${x}`)
            .join(", ");
          console.log(
            `${e.name.padEnd(16)}  ${e.format.padEnd(12)}  → ${e.outDir}/${e.outName}`
          );
          console.log(`  ${v}`);
        }
        return;
      }

      const selected = opts.entry
        ? config.entries.filter((e) => e.name === opts.entry)
        : config.entries;

      if (selected.length === 0) {
        error(
          opts.entry
            ? `No entry named "${opts.entry}" in vendor.config.ts`
            : "vendor.config.ts has no entries"
        );
        process.exit(1);
      }

      // --check only needs vendor/package.json + manifest.json + on-disk
      // artifacts. It never rebuilds, so node_modules is not required.
      if (!opts.check) {
        await ensureInstalled();
      }

      for (const e of selected) {
        log(`Building entry: ${e.name}`);
        try {
          await buildEntry(e, { check: !!opts.check });
        } catch (err) {
          error(`Entry "${e.name}" failed: ${(err as Error).message}`);
          process.exit(1);
        }
      }

      if (opts.check && process.exitCode === 1) {
        process.exit(1);
      }
    }
  );
